### ISSUE TITLE
Throwing error during npm run serve

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-pam-auth#10]
Hi,
I get follow error when I'm using osjs-pam-auth:
```
/home/milad/WebstormProjects/nodejs/OS.js/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
```
**src/server/config.js:**
```js
vfs: {
    root: '/home',
    mountpoints: [{....
```
**src/server/index.js:**
```js
const pamAuth = require('@osjs/pam-auth');
osjs.register(AuthServiceProvider, {
  args: {
    adapter: pamAuth
  }
});
```

> "@osjs/pam-auth": "^1.2.0",

**Comment by miladhashemi** [comment]
It seems problem is here **line 30**:
**src/authenticate.js:**
`const userid = require('userid'); // TODO FIXME We don't need this anymore ?!`
I commented this line, now npm run serve being done successfuly.

**Comment by andersevenrud** [comment]
Could you paste the entire ouput ot  `npm run serve` please ?

**Comment by miladhashemi** [comment]
I can't regenerate this error again, even I cloned clean OS.js from github and then install pam-auth package again, but I didn't get that error again.
Maybe after installing libpam-dev, I had to restart shell or pc and then execute npm run serve.
>  `const userid = require('userid'); // TODO FIXME We don't need this anymore ?!`
>  I commented this line, now npm run serve being done successfuly.

Anyway, this line wasn't problem.

**Comment by andersevenrud** [comment]
Sounds to me like maybe something went wrong during `npm install` at one point.

So it's safe to close this ? :)

**Comment by miladhashemi** [comment]
> Sounds to me like maybe something went wrong during npm install at one point.

Maybe.

> So it's safe to close this ? :)

Thank U. Yes
