### ISSUE TITLE
Doesn't grab the primary user group

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-pam-auth#5]
When the user is logged in, PAM forgets to add the primary group to the array of users.

**Comment by andersevenrud** [comment]
PAM is not at fault here. PAM only handles the authentication. What is wrong here is that I don't correctly detect what groups are assigned:

https://github.com/os-js/osjs-pam-auth/blob/master/index.js#L35

**Comment by andersevenrud** [comment]
I've published a new release that should fix this issue.
