### ISSUE TITLE
Feature request: Restrict login to certain groups

### ISSUE THREAD

**Issue by IngwiePhoenix** [os-js/osjs-pam-auth#6]
It would be nice being able to tell the service provider to only allow certain users to be able to log into the OS.js desktop.

Reason:
- Currently, running OS.js as a non-root results in the inability to log into other user accounts.
- The workaround: Run as root - restrict logins, preferably by group, but maybe only by individual accounts as well.

**Comment by andersevenrud** [comment]
>  Currently, running OS.js as a non-root results in the inability to log into other user accounts.

This is related to https://github.com/os-js/osjs-pam-auth/issues/1

I want to make a "OS.js host service" that this adapter to hook into to make calls as a privileged user over RPC.

**Comment by andersevenrud** [comment]
In the case of restriction based on user groups, it would just require to wrap this promise to check the groups and reject based on a configuration setting.

https://github.com/os-js/osjs-pam-auth/blob/master/index.js#L95

**Comment by andersevenrud** [comment]
This was added in https://github.com/os-js/osjs-server/commit/363e761ac72c3a6073f89acfb2e997e85cfe77c7
